# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UNOS_login(object):
    def setupUi(self, UNOS_login):
        UNOS_login.setObjectName("UNOS_login")
        UNOS_login.resize(800, 600)
        self.widget_login = QtWidgets.QWidget(UNOS_login)
        self.widget_login.setGeometry(QtCore.QRect(0, 0, 801, 611))
        self.widget_login.setStyleSheet("QWidget#widget_login{\n"
"background-color:\n"
"qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(61, 145, 255, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget_login.setObjectName("widget_login")
        self.label = QtWidgets.QLabel(self.widget_login)
        self.label.setGeometry(QtCore.QRect(290, 150, 221, 41))
        self.label.setStyleSheet("font: 26pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_login)
        self.label_2.setGeometry(QtCore.QRect(290, 200, 131, 31))
        self.label_2.setStyleSheet("font: 13pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_login)
        self.label_3.setGeometry(QtCore.QRect(290, 280, 131, 31))
        self.label_3.setStyleSheet("font: 13pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.lineEdit_username = QtWidgets.QLineEdit(self.widget_login)
        self.lineEdit_username.setGeometry(QtCore.QRect(290, 230, 221, 31))
        self.lineEdit_username.setText("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget_login)
        self.lineEdit_password.setGeometry(QtCore.QRect(290, 310, 221, 31))
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.QpushButton_login = QtWidgets.QPushButton(self.widget_login)
        self.QpushButton_login.setGeometry(QtCore.QRect(300, 360, 201, 51))
        self.QpushButton_login.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(0, 170, 127);\n"
"font: 20pt \"MS Shell Dlg 2\"; color: rgb(255, 255, 255)")
        self.QpushButton_login.setObjectName("QpushButton_login")

        self.retranslateUi(UNOS_login)
        QtCore.QMetaObject.connectSlotsByName(UNOS_login)

    def retranslateUi(self, UNOS_login):
        _translate = QtCore.QCoreApplication.translate
        UNOS_login.setWindowTitle(_translate("UNOS_login", "Unet updater please login in"))
        self.label.setText(_translate("UNOS_login", "UNET Login :"))
        self.label_2.setText(_translate("UNOS_login", "Unet User name:"))
        self.label_3.setText(_translate("UNOS_login", "Unet Password:"))
        self.QpushButton_login.setText(_translate("UNOS_login", "Log in"))
